name: Create a new test round on arbitrum goerli

on: workflow_dispatch

env:
  NODE_VERSION: 16.x
  FACTORY_ADDRESS: 0x62cab00605368834c6adf8e6f53da14d6fa9ded1
  USER_REGISTRY_TYPE: brightid
  BRIGHTID_SPONSOR: 0xC7c81634Dac2de4E7f2Ba407B638ff003ce4534C
  BRIGHTID_VERIFIER_ADDR:  0xb1d71F62bEe34E9Fc349234C201090c33BCdF6DB
  WALLET_PRIVATE_KEY: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}

jobs:
  setup-and-tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Build CLR
      run: |
        yarn && yarn build
    - name: Run create new round script
      run: |
        cd contracts
        yarn hardhat run scripts/newRound.ts --network arbitrum-goerli
